[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.R, config={align = "cm", minh = 1.75, minw = 1.5,padding = 0.05, r = 0.1, hover = true, colour = G.C.ORANGE, button = "options", shadow = true}, nodes={'''
position = "before"
payload = '''
{n=G.UIT.R, config={id = 'suikabb_toggle_button',align = "cm", minh = 1.05, minw = 1.5,padding = 0.05, r = 0.1, hover = true, colour = G.C.GREEN, button = "enable_or_disable_suika", shadow = true}, nodes={
    {n=G.UIT.C, config={align = "cm", maxw = 1.4, focus_args = {button = 'start', orientation = 'bm'}, func = 'suikabb_button'}, nodes={
        {n=G.UIT.T, config={text = 'Suika', scale = scale, colour = G.C.UI.TEXT_LIGHT, shadow = true}}
    }},
}},
'''
match_indent = true
